# Generated by Django 2.1.5 on 2019-02-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='contenido',
            field=models.FileField(blank=True, null=True, upload_to='archivos/imagenes/%Y%m%D/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='contenido',
            field=models.FileField(upload_to='archivos/audios/%Y%m%D/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='contenido',
            field=models.FileField(upload_to='archivos/videos/%Y%m%D/'),
        ),
    ]
