# Generated by Django 2.1.5 on 2019-02-09 23:04

from django.db import migrations, models
import galeria.validators


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20190203_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='contenido',
            field=models.FileField(upload_to='archivos/audios/%Y%m%D/', validators=[galeria.validators.validar_audio]),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='contenido',
            field=models.FileField(blank=True, null=True, upload_to='archivos/imagenes/%Y%m%D/', validators=[galeria.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(upload_to='archivos/fotos_usuarios'),
        ),
        migrations.AlterField(
            model_name='video',
            name='contenido',
            field=models.FileField(upload_to='archivos/videos/%Y%m%D/', validators=[galeria.validators.validar_video]),
        ),
    ]
