# Generated by Django 2.1.5 on 2019-02-10 02:27

from django.db import migrations, models
import galeria.validators


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20190209_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='contenido',
            field=models.FileField(upload_to='audios/', validators=[galeria.validators.validar_audio]),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='contenido',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/', validators=[galeria.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='video',
            name='contenido',
            field=models.FileField(upload_to='videos/', validators=[galeria.validators.validar_video]),
        ),
    ]
